# Generated by Django 2.0.13 on 2019-07-11 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0003_auto_20190711_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixageral',
            name='dataDeCadastro',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dataDeCadastro',
            field=models.DateTimeField(blank=True),
        ),
    ]
