# Generated by Django 2.0.13 on 2019-07-12 19:26

from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0005_auto_20190712_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacaoentrada',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doacaoentrada',
            name='valor',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='BRL', max_digits=11, validators=[djmoney.models.validators.MinMoneyValidator(0.01), djmoney.models.validators.MaxMoneyValidator(9999999.99)]),
        ),
        migrations.AlterField(
            model_name='doacaoentrada',
            name='valor_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'BRL R$')], default='BRL', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='doacaosaida',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doacaosaida',
            name='valor_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'BRL R$')], default='BRL', editable=False, max_length=3),
        ),
    ]
