# Generated by Django 2.0.13 on 2019-07-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0006_auto_20190712_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixageral',
            name='saldo_currency',
        ),
        migrations.RemoveField(
            model_name='doacaoentrada',
            name='valor_currency',
        ),
        migrations.RemoveField(
            model_name='doacaosaida',
            name='valor_currency',
        ),
        migrations.AlterField(
            model_name='caixageral',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='doacaoentrada',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='doacaosaida',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
