# Generated by Django 2.0.13 on 2019-07-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0008_auto_20190712_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixageral',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='doacaoentrada',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doacaosaida',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11),
        ),
    ]
