# Generated by Django 2.0.13 on 2019-07-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0009_auto_20190712_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixageral',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
