# Generated by Django 2.0.13 on 2019-07-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0010_auto_20190712_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacaoentrada',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
