# Generated by Django 2.0.13 on 2019-07-31 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0012_auto_20190730_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacaoentrada',
            name='outrasDoacoes',
        ),
        migrations.RemoveField(
            model_name='doacaosaida',
            name='outrasDoacoes',
        ),
        migrations.RemoveField(
            model_name='produtodoacao',
            name='quantiaDoacao',
        ),
        migrations.AddField(
            model_name='doacaoentrada',
            name='quantiaDoacao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='doacaosaida',
            name='quantiaDoacao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='doacaoentrada',
            name='produtoDoacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='anjosDePlantaoAmbiente.ProdutoDoacao'),
        ),
        migrations.AlterField(
            model_name='doacaosaida',
            name='produtoDoacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='anjosDePlantaoAmbiente.ProdutoDoacao'),
        ),
        migrations.AlterField(
            model_name='produtodoacao',
            name='saldoEstoque',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
