# Generated by Django 2.0.13 on 2019-08-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0013_auto_20190731_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='transacao',
        ),
        migrations.RenameField(
            model_name='produtodoacao',
            old_name='dataCadastro',
            new_name='dataDeCadastro',
        ),
        migrations.AlterField(
            model_name='doacaoentrada',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='doacaosaida',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
