# Generated by Django 2.0.13 on 2019-08-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0014_auto_20190805_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_busca', models.CharField(choices=[('pessoa', 'Pessoa'), ('evento', 'Evento'), ('produto', 'Produto'), ('usuario', 'Usuário'), ('doacao_entrada', 'Entrada de Doação'), ('doacao_saida', 'Saida de Doação')], default='pessoa', max_length=10)),
                ('texto_busca', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
