# Generated by Django 2.0.13 on 2019-08-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0015_busca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busca',
            name='tipo_busca',
            field=models.CharField(choices=[('pessoa', 'Pessoa'), ('evento', 'Evento'), ('produto', 'Produto'), ('usuario', 'Usuário'), ('doacao_entrada', 'Entrada de Doação'), ('doacao_saida', 'Saida de Doação')], default='pessoa', max_length=15),
        ),
    ]
