# Generated by Django 2.0.13 on 2019-08-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0016_auto_20190808_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busca',
            name='tipo_busca',
            field=models.CharField(choices=[('pessoa', 'Pessoa'), ('evento', 'Evento'), ('produto', 'Produto'), ('usuario', 'Usuário'), ('doacao_entrada', 'Doações Recebidas'), ('doacao_saida', 'Doações Realizadas')], default='pessoa', max_length=15),
        ),
    ]
