# Generated by Django 2.0.13 on 2019-08-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0017_auto_20190812_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cadastro_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
