# Generated by Django 2.0.13 on 2019-08-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0018_pessoa_cadastro_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtodoacao',
            name='cadastro_ativo',
            field=models.CharField(blank=True, default='Sim', max_length=3),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cadastro_ativo',
            field=models.CharField(blank=True, default='Sim', max_length=3),
        ),
    ]
