# Generated by Django 2.0.13 on 2019-08-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0019_auto_20190816_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixageral',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11),
        ),
    ]
