# Generated by Django 2.0.13 on 2019-08-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0020_auto_20190819_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='busca',
            name='cadastro_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
