# Generated by Django 2.0.13 on 2019-08-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0021_busca_cadastro_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busca',
            name='cadastro_ativo',
        ),
        migrations.AddField(
            model_name='busca',
            name='status_cadastro',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=8),
        ),
    ]
