# Generated by Django 2.0.13 on 2019-08-28 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0022_auto_20190819_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoDoado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anjosDePlantaoAmbiente.ProdutoDoacao')),
            ],
        ),
        migrations.AlterField(
            model_name='doacaoentrada',
            name='produtoDoacao',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='anjosDePlantaoAmbiente.ProdutoDoacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doacaoentrada',
            name='quantiaDoacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
