# Generated by Django 2.0.13 on 2019-08-28 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0027_doacaoentrada_listaprodutos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacaoentrada',
            name='listaProdutos',
        ),
        migrations.AddField(
            model_name='doacaoentrada',
            name='listaProdutos',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='anjosDePlantaoAmbiente.ProdutoDoado'),
            preserve_default=False,
        ),
    ]
