# Generated by Django 2.0.13 on 2019-08-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0030_doacaoentrada_listaprodutos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacaoentrada',
            name='listaProdutos',
        ),
        migrations.AddField(
            model_name='produtodoado',
            name='doacaoReferenciaPK',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
