# Generated by Django 2.0.13 on 2019-09-01 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0031_auto_20190831_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoDoadoSaida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doacaoReferenciaPK', models.PositiveIntegerField(null=True)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anjosDePlantaoAmbiente.ProdutoDoacao')),
            ],
        ),
        migrations.AlterField(
            model_name='doacaoentrada',
            name='produtoDoacao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='anjosDePlantaoAmbiente.ProdutoDoacao'),
        ),
        migrations.AlterField(
            model_name='doacaosaida',
            name='produtoDoacao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='anjosDePlantaoAmbiente.ProdutoDoacao'),
        ),
        migrations.AlterField(
            model_name='doacaosaida',
            name='quantiaDoacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
