# Generated by Django 2.0.13 on 2019-09-02 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0034_auto_20190901_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacaoentrada',
            name='produtoDoacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='anjosDePlantaoAmbiente.ProdutoDoacao'),
        ),
        migrations.AlterField(
            model_name='doacaosaida',
            name='produtoDoacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='anjosDePlantaoAmbiente.ProdutoDoacao'),
        ),
    ]
