# Generated by Django 2.0.13 on 2019-09-02 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0040_auto_20190901_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacaosaida',
            name='produtoDoacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='anjosDePlantaoAmbiente.ProdutoDoacao'),
        ),
    ]
