# Generated by Django 2.0.13 on 2019-09-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0042_auto_20190901_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacaoentrada',
            name='quantiaDoacao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='doacaosaida',
            name='quantiaDoacao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
