# Generated by Django 2.0.13 on 2019-09-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0044_auto_20190902_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixageral',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
