# Generated by Django 2.0.13 on 2019-09-09 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0045_auto_20190906_2211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdutoDoado',
            new_name='ProdutoDoadoEntrada',
        ),
    ]
