# Generated by Django 2.0.13 on 2019-09-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anjosDePlantaoAmbiente', '0046_auto_20190909_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixageral',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
