# Generated by Django 2.0.13 on 2019-07-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
