# Generated by Django 2.0.13 on 2019-08-13 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_auto_20190812_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
