# Generated by Django 2.0.13 on 2019-08-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_auto_20190812_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cadastro_ativo',
            field=models.CharField(blank=True, default='Sim', max_length=3),
        ),
    ]
